server:
  port: 8081
  
spring:
  config:
    import: configserver:http://localhost:8888
  application:
    name: 'fornecedor'  

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka      